### PR TITLE
Light Mode Interaction States - NxCombobox - RSC-1465

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1465

### CODE REVIEW

**Comment by EmilyBermudez88** [comment]
I just noticed (related to this ticket, but I missed it in the dropdown ticket), that on hover, the items in NxDropdownMenu are supposed to have the colour `--nx-color-text-dark`. Putting a ticket in now to fix that, which will fix this.

**Review by EmilyBermudez88 — COMMENTED** [review]
on line 245 for the visual tests, 'it has a light blue border and light blue background when clicked' should now be 'it has a light grey background when clicked'

**Comment by avnvbhatta** [comment]
> on line 245 for the visual tests, 'it has a light blue border and light blue background when clicked' should now be 'it has a light grey background when clicked'

Updated here: 3540c120fca773189285f0a825a38e443500d25e

**Comment by EmilyBermudez88** [comment]
One final thing that I'm unsure about- in the dropdown for combobox, if an item is 'selected' with the arrow keys, does the text need to darken as well? This wasn't something needed for NxDropdownMenu, but it seems as though that behaviour exists in NxList, so not sure if it's relevant here (since NxDropdown is supposed to copy relevant styles from NxList)

**Comment by avnvbhatta** [comment]
> 



> One final thing that I'm unsure about- in the dropdown for combobox, if an item is 'selected' with the arrow keys, does the text need to darken as well? This wasn't something needed for NxDropdownMenu, but it seems as though that behaviour exists in NxList, so not sure if it's relevant here (since NxDropdown is supposed to copy relevant styles from NxList)

I would consult with Jason about it. There isn't exactly a "selected" state for dropdowns, and the combobox behaves a bit differently in terms of how we interact with the menu items. But regardless, it seems like a good idea to add it. I would still confirm with Jason, and if he agrees, then Kaleido needs to be updated as well. Currently, there aren't mocks for combobox menu items.

**Comment by avnvbhatta** [comment]
> One final thing that I'm unsure about- in the dropdown for combobox, if an item is 'selected' with the arrow keys, does the text need to darken as well? This wasn't something needed for NxDropdownMenu, but it seems as though that behaviour exists in NxList, so not sure if it's relevant here (since NxDropdown is supposed to copy relevant styles from NxList)

I talked to @JasonDSwearingen and made the change here: 25b2ba448ea291561aa49c227fc3c98577c00903

**Review by EmilyBermudez88 — APPROVED** [review]
LGTM!

**Pull request merged**
