### PR TITLE
Dark Mode Submit Mask - RSC-1041

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-1041

### CODE REVIEW

**Comment by avnvbhatta** [comment]
The background of the mask looks like it's been changed. Should be `Hsla(229, 44%, 5%, 0.7)`

**Comment by avnvbhatta** [comment]
> The background of the mask looks like it's been changed. Should be `Hsla(229, 44%, 5%, 0.7)`. Maybe need to reach out to Jason for the specific swatch color. Sketch doesn't seem to have it.

**Comment by rpokorny** [comment]
> Should be Hsla(229, 44%, 5%, 0.7). Maybe need to reach out to Jason for the specific swatch color. Sketch doesn't seem to have it.

I think it's indigo-5 with a rounding error.  However that mockup still confuses me in that it appears to have opacity applied in two different ways: The color itself has an alpha channel of 0.7, but sketch also shows an opacity property of 75%.  Interpreting that literally would lead me to believe that the true opacity of the mask should be 0.7 * 0.75 = 0.525.  However I suspect it's actually a mockup mistake.  @JasonDSwearingen please confirm.

**Comment by rpokorny** [comment]
> I think it's indigo-5 with a rounding error. However that mockup still confuses me in that it appears to have opacity applied in two different ways: The color itself has an alpha channel of 0.7, but sketch also shows an opacity property of 75%. Interpreting that literally would lead me to believe that the true opacity of the mask should be 0.7 * 0.75 = 0.525. However I suspect it's actually a mockup mistake. @JasonDSwearingen please confirm.

Tentatively updated: 3f2bd2a18

**Comment by rpokorny** [comment]
> Tentatively updated: https://github.com/sonatype/sonatype-react-shared-components/commit/3f2bd2a1819a96fe4b0cb0913fc931c2d865b39d

Finalized: 244e24890

**Review by EmilyBermudez88 — APPROVED** [review]
LGTM!

**Pull request merged**
