### PR TITLE
Update tooltip styles - RSC-148

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-148

### CODE REVIEW

**Comment by glenhunter** [comment]
The Zeplin file is showing the tooltips as semi-bold

**Comment by glenhunter** [comment]
We should probably have an example that shows long content wrapping as in the Zeplin file

**Comment by rpokorny** [comment]
> The Zeplin file is showing the tooltips as semi-bold

It was also in the wrong font face. 2f87ea5d

**Comment by rpokorny** [comment]
> We should probably have an example that shows long content wrapping as in the Zeplin file

0a8577aa

**Comment by glenhunter** [comment]
Safari problems:
Screen Shot 2020-12-07 at 1 23 10 PM
Screen Shot 2020-12-07 at 1 22 59 PM
Screen Shot 2020-12-07 at 1 22 55 PM
Seems like it has something to do with the radio button. Might be better in general to have these laid out in "correct" form layout styles to make sure there are no issues there especially since that's how we expect the form elements to be used?

**Comment by rpokorny** [comment]
> Safari problems:

Are you referring to the fact that the tooltip alignment doesn't work the same for the filter input vs the normal input?  That's the case in Chrome as well, and I doubt it's specifically to do with the non-standardness of that page.  I'll look into it.

**Comment by glenhunter** [comment]
> > Safari problems:
> 
> Are you referring to the fact that the tooltip alignment doesn't work the same for the filter input vs the normal input? That's the case in Chrome as well, and I doubt it's specifically to do with the non-standardness of that page. I'll look into it.

See the way in the screenshots how the tooltip is slightly indented and partially covers the text input

**Comment by rpokorny** [comment]
> See the way in the screenshots how the tooltip is slightly indented and partially covers the text input

Pre-existing issue.  I've made a but ticket for it. https://issues.sonatype.org/browse/RSC-408

**Review by glenhunter — APPROVED** [review]

**Pull request merged**
