### PR TITLE
Add Close button to NxAlert - RSC-18

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-18

Adds Close buttons to `NxAlert` along with clarifications to the documentation for `NxLoadError` and `NxLoadWrapper` on when this close button should be used in comparison to the Retry button provided by those components.

### CODE REVIEW

**Comment by glenhunter** [comment]
In Zeplin the design suggests that the border of the close button should be 16px from top, right, and Botton to the edge of the alert, but in NxAlert the edge of the button appears to be 8px from the top/bottom.

**Comment by glenhunter** [comment]
In this case I find the white background of the buttons to be quite ugly on the different colored alert backgrounds. 
Screen Shot 2020-08-10 at 4 26 34 PM

**Comment by dturner32** [comment]
> I find the white background of the buttons to be quite ugly on the different colored alert backgrounds.
> Screen Shot 2020-08-10 at 4 26 34 PM

I can't remember if I specified that the tertiary and secondary buttons get a white background or not but I will now. They shouldn't have white backgrounds in their default state. Only background colors secondary and tertiary buttons receive is on hover or click

**Comment by rpokorny** [comment]
> I can't remember if I specified that the tertiary and secondary buttons get a white background or not but I will now. They shouldn't have white backgrounds in their default state. Only background colors secondary and tertiary buttons receive is on hover or click

If I'm not mistaken the screenshot is of the hover state.

**Comment by rpokorny** [comment]
> I can't remember if I specified that the tertiary and secondary buttons get a white background or not but I will now. They shouldn't have white backgrounds in their default state. Only background colors secondary and tertiary buttons receive is on hover or click

Relevant slack thread: https://sonatype.slack.com/archives/CJUF9G7T2/p1591970758404800

**Comment by dturner32** [comment]
> > I can't remember if I specified that the tertiary and secondary buttons get a white background or not but I will now. They shouldn't have white backgrounds in their default state. Only background colors secondary and tertiary buttons receive is on hover or click
> 
> If I'm not mistaken the screenshot is of the hover state.



> > I can't remember if I specified that the tertiary and secondary buttons get a white background or not but I will now. They shouldn't have white backgrounds in their default state. Only background colors secondary and tertiary buttons receive is on hover or click
> 
> If I'm not mistaken the screenshot is of the hover state.

based on what's in Zeplin, the white background applies to the click state for the close button which follows the tertiary button pattern. However, to Glen's point I agree that white background feels a bit odd on color. This is an instance, only in the case of a close button, where I would be willing to go against using the white background tertiary styling and just have the 'click' state be the same as the 'hover' state if that makes sense. Currently, the close button only appears in modals and alerts so I don't  think it would be too big of a visual discourse to tweak the tertiary standard here

**Comment by rpokorny** [comment]
> where I would be willing to go against using the white background tertiary styling and just have the 'click' state be the same as the 'hover' state if that makes sense.

But I've just confirmed, this screenshot is in fact the hover state.  The click state has a grey background.

If you want to create a special case here could you clarify which of the following makes the most sense to be the special case:

* All Close buttons in Alerts should deviate from the tertiary styles
* All Close buttons anywhere should deviate from the tertiary styles
* All tertiary buttons in Alerts should deviate from the tertiary styles.

Note that based on past conversations it is already such that for the **default** state, all Close buttons in Alerts deviate from the tertiary styles (in that they have a transparent background instead of a light grey background.  Additionally, all Close buttons (whether within an Alert or not) deviate from the tertiary styles in that they have nor border in the default state.

**Comment by dturner32** [comment]
> > where I would be willing to go against using the white background tertiary styling and just have the 'click' state be the same as the 'hover' state if that makes sense.
> 
> But I've just confirmed, this screenshot is in fact the hover state. The click state has a grey background.
> 
> If you want to create a special case here could you clarify which of the following makes the most sense to be the special case:
> 
> * All Close buttons in Alerts should deviate from the tertiary styles
> * All Close buttons anywhere should deviate from the tertiary styles
> * All tertiary buttons in Alerts should deviate from the tertiary styles.
> 
> Note that based on past conversations it is already such that for the **default** state, all Close buttons in Alerts deviate from the tertiary styles (in that they have a transparent background instead of a light grey background. Additionally, all Close buttons (whether within an Alert or not) deviate from the tertiary styles in that they have nor border in the default state.

all close buttons anywhere should deviate from tertiary styles

**Comment by rpokorny** [comment]
> all close buttons anywhere should deviate from tertiary styles

@dturner32 Looking back through various conversations we've had, I believe some inconsistent things have been said about what these buttons are supposed to look like, so I want to get it all clarified here if possible.  Ideally, if you could provide a zeplin mock with all the close button states within an alert (similar to what you displayed as a static image [here](https://sonatype.slack.com/archives/CJUF9G7T2/p1591973275407200?thread_ts=1591970758.404800&cid=CJUF9G7T2), that would probably answer everything.

So, first question, should there be any difference at all between a Close button in general and a Close button in an alert?

Then, please point out all changes you want to the following which describes how things are at the moment:

Default state: general Close buttons have a white background and no border.  Alert Close buttons have no background and no border
Hover state: matches the tertiary styles entirely (white background, dark grey border)
Click state: matches the tertiary styles entirely (grey background, dark grey border)

**Comment by dturner32** [comment]
> > all close buttons anywhere should deviate from tertiary styles
> 
> @dturner32 Looking back through various conversations we've had, I believe some inconsistent things have been said about what these buttons are supposed to look like, so I want to get it all clarified here if possible. Ideally, if you could provide a zeplin mock with all the close button states within an alert (similar to what you displayed as a static image [here](https://sonatype.slack.com/archives/CJUF9G7T2/p1591973275407200?thread_ts=1591970758.404800&cid=CJUF9G7T2), that would probably answer everything.
> 
> So, first question, should there be any difference at all between a Close button in general and a Close button in an alert?
> 
> Then, please point out all changes you want to the following which describes how things are at the moment:
> 
> Default state: general Close buttons have a white background and no border. Alert Close buttons have no background and no border
> Hover state: matches the tertiary styles entirely (white background, dark grey border)
> Click state: matches the tertiary styles entirely (grey background, dark grey border)

to answer the first question, there will be a distinct stylistic separation between standard close buttons and close buttons within alerts. (I will do a quick mockup to show the differences) 

standard close buttons (anything not on a colored background) will continue to follow the tertiary styling

in the case of a close button in an alert, tertiary styling will not be used and these will only have a hover and click state

**Comment by rpokorny** [comment]
> standard close buttons (anything not on a colored background) will continue to follow the tertiary styling

This is in direct contradiction to what you said when I first implemented Close buttons, [here](https://sonatype.slack.com/archives/CJUF9G7T2/p1591979438412300?thread_ts=1591970758.404800&cid=CJUF9G7T2)

**Comment by dturner32** [comment]
> > standard close buttons (anything not on a colored background) will continue to follow the tertiary styling
> 
> This is in direct contradiction to what you said when I first implemented Close buttons, [here](https://sonatype.slack.com/archives/CJUF9G7T2/p1591979438412300?thread_ts=1591970758.404800&cid=CJUF9G7T2)

sorry for the confusion, yes based on the conversation that we had in Slack I said that the close button will maintain all the tertiary styles minus the border on default

**Comment by dturner32** [comment]
> > > standard close buttons (anything not on a colored background) will continue to follow the tertiary styling
> > 
> > 
> > This is in direct contradiction to what you said when I first implemented Close buttons, [here](https://sonatype.slack.com/archives/CJUF9G7T2/p1591979438412300?thread_ts=1591970758.404800&cid=CJUF9G7T2)
> 
> sorry for the confusion, yes based on the conversation that we had in Slack I said that the close button will maintain all the tertiary styles minus the border on default

if that is what you have implemented then it should be fine for the standard close button

**Comment by rpokorny** [comment]
> in the case of a close button in an alert, tertiary styling will not be used and these will only have a hover and click state

@dturner32 I'll await a zeplin mockup indicating exactly how that should be.

**Comment by dturner32** [comment]
> > in the case of a close button in an alert, tertiary styling will not be used and these will only have a hover and click state
> 
> @dturner32 I'll await a zeplin mockup indicating exactly how that should be.

@rpokorny close buttons states for alerts and general usage have been added in zeplin

**Comment by rpokorny** [comment]
Updated to match latest zeplin mockups. 3f8a83e7

**Comment by glenhunter** [comment]
> along with clarifications to the documentation for NxLoadError and NxLoadWrapper on when this close button should be used in comparison to the Retry button provided by those components.

I didn't see any documentation in NxLoadWrapper about `onClose`.

**Comment by rpokorny** [comment]
> I didn't see any documentation in NxLoadWrapper about onClose.

I was referring there to the new documentation of the fact that omitting the `retryHandler` in `NxLoadWrapper` is now deprecated.

**Pull request merged**
