### PR TITLE
NxCollapsible(Radio|Multi)Select Clear Button Alignment - RSC-1509

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1509

### CODE REVIEW

**Review by entroform — APPROVED** [review]
LGTM

**Comment by EmilyBermudez88** [comment]
Screenshot 2023-03-20 at 9 25 48 AM
Screenshot 2023-03-20 at 9 26 49 AM
It looks as though the right spacing is a bit off. It looks like it's supposed to be 6px in Sketch, but 8px here. (I recreated the focus state on main to check, I'm not on the interaction state branch in case you're wondering ;) )

**Comment by avnvbhatta** [comment]
> 



> Screenshot 2023-03-20 at 9 32 14 AM Screenshot 2023-03-20 at 9 25 48 AM
> 
> It looks as though the right spacing is a bit off. It looks like it's supposed to be 6px in Sketch, but 8px here. (I recreated the focus state on your branch to check, I'm not on the interaction state branch in case you're wondering ;) )

Looks like this was never implemented. Fixed here: 3e79c842e1063567bb531bfa0985cb20dff4cd5b

Also, since this issue isn't really a part of interactions states, I think I'll wait until we merge the interaction states feature branch to be merged first before running the visual tests. This PR is going to cause new snapshot updates, so I'll wait until the feature branch is merged before working on this further.

**Comment by EmilyBermudez88** [comment]
> Also, since this issue isn't really a part of interactions states, I think I'll wait until we merge the interaction states feature branch to be merged first before running the visual tests. This PR is going to cause new snapshot updates, so I'll wait until the feature branch is merged before working on this further.

Yep makes sense!

**Pull request merged**
