### PR TITLE
Dark Mode - NxGlobalSidebar - Update icon color - RSC-1687

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1687

### CODE REVIEW

**Comment by EmilyBermudez88** [comment]
You'll likely need to update the snapshots for everything that uses the sidebar in its tests. Taking a quick peak, it looks like breadcrumb, global header, global sidebar footer, submit mask, toast & page layout (although I may have missed one somewhere)

**Comment by rpokorny** [comment]
PR title should say `NxGlobalSidebar`, not `NxGlobalHeader`

**Comment by rpokorny** [comment]
Another issue, which IMO could also be fixed in this PR: the dark mode default text color for these links is not white it's indigo-97

**Comment by EmilyBermudez88** [comment]
> Another issue, which IMO could also be fixed in this PR: the dark mode default text color for these links is not white it's indigo-97

Interesting, it's inconsistent in the mocks. 2 examples are white and one is indigo-97

**Comment by avnvbhatta** [comment]
> You'll likely need to update the snapshots for everything that uses the sidebar in its tests. Taking a quick peak, it looks like breadcrumb, global header, global sidebar footer, submit mask, toast & page layout (although I may have missed one somewhere)

Updated here: 6c2c373a17d7e647f0aaa306023e6733150b485e

**Comment by avnvbhatta** [comment]
> > Another issue, which IMO could also be fixed in this PR: the dark mode default text color for these links is not white it's indigo-97
> 
> Interesting, it's inconsistent in the mocks. 2 examples are white and one is indigo-97

Based on Jenni's response, looks like it was a mockup error and current implementation should be good?

**Comment by EmilyBermudez88** [comment]
> > You'll likely need to update the snapshots for everything that uses the sidebar in its tests. Taking a quick peak, it looks like breadcrumb, global header, global sidebar footer, submit mask, toast & page layout (although I may have missed one somewhere)
> 
> Updated here: [6c2c373](https://github.com/sonatype/sonatype-react-shared-components/commit/6c2c373a17d7e647f0aaa306023e6733150b485e)

Looks like some breadcrumb snapshots snuck in that shouldn't be there (just the one including the global sidebar). The  color fixes regarding the ' / ' were done in the breadcrumb dark mode ticket

**Comment by avnvbhatta** [comment]
> > > You'll likely need to update the snapshots for everything that uses the sidebar in its tests. Taking a quick peak, it looks like breadcrumb, global header, global sidebar footer, submit mask, toast & page layout (although I may have missed one somewhere)
> > 
> > 
> > Updated here: [6c2c373](https://github.com/sonatype/sonatype-react-shared-components/commit/6c2c373a17d7e647f0aaa306023e6733150b485e)
> 
> Looks like some breadcrumb snapshots snuck in that shouldn't be there (just the one including the global sidebar). The color fixes regarding the ' / ' were done in the breadcrumb dark mode ticket

Looks like we updated the color and forgot to push the updated snapshots. These can just be updated in this PR.

**Comment by avnvbhatta** [comment]
> > > You'll likely need to update the snapshots for everything that uses the sidebar in its tests. Taking a quick peak, it looks like breadcrumb, global header, global sidebar footer, submit mask, toast & page layout (although I may have missed one somewhere)
> > 
> > 
> > Updated here: [6c2c373](https://github.com/sonatype/sonatype-react-shared-components/commit/6c2c373a17d7e647f0aaa306023e6733150b485e)
> 
> Looks like some breadcrumb snapshots snuck in that shouldn't be there (just the one including the global sidebar). The color fixes regarding the ' / ' were done in the breadcrumb dark mode ticket


Looks like we updated the color and forgot to push the updated snapshots. Should now only contain one relevant update to the breadcrumb snapshots: bd05bdf2a4489af476ee61b37bec267b6812f99f

**Review by rpokorny — APPROVED** [review]

**Pull request merged**
