### PR TITLE
Use NxTooltip for NxTransferList Reordering Tooltips - RSC-1113

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-1113

### CODE REVIEW

**Review by JenniKobylski — APPROVED** [review]
Great!

**Comment by EmilyBermudez88** [comment]
As I'm testing it out, I'm getting this error in the console: 
Screen Shot 2022-09-13 at 11 35 30 AM

**Comment by rpokorny** [comment]
> As I'm testing it out, I'm getting this error in the console:

Yes, I'd noticed that during design PR review but hadn't gotten a chance to look into it yet.  Thanks.  Fixed in 2d885f6cf

**Comment by EmilyBermudez88** [comment]
I noticed this morning that if you have something in focus that has a tooltip and then scroll through the item list, the tooltip doesn't disappear at the top of the `.nx-transfer-list__item-list`, but keeps drifting above it's container. 

Screen Shot 2022-09-14 at 9 06 55 AM

**Comment by rpokorny** [comment]
> It this an edge case we wouldn't need to worry about?

That's normal for MUI tooltips, I don't think we should worry about it

**Comment by EmilyBermudez88** [comment]
> > It this an edge case we wouldn't need to worry about?
> 
> That's normal for MUI tooltips, I don't think we should worry about it

Ok, if that's the case, then everything else looks good!

**Review by EmilyBermudez88 — APPROVED** [review]

**Pull request merged**
