### PR TITLE
Adjust NxAlert Height when close Button is not Present - RSC-1114

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-1114

I recommend viewing the `NxLoadError.scss` changes with "Hide whitespace"

### CODE REVIEW

**Comment by EmilyBermudez88** [comment]
I'm reading through the ensureElement function and wondering if there are scenarios in which isReactText(content) is false, which would result in the content NOT being wrapped in a <span> element?

**Review by EmilyBermudez88 — APPROVED** [review]

**Comment by rpokorny** [comment]
> I'm reading through the ensureElement function and wondering if there are scenarios in which isReactText(content) is false, which would result in the content NOT being wrapped in a span element?

I don't think that's an issue but you did help me realize that `ensureElement` did things other than what its name implied, which are needed in many other areas but which were not what we want here.  So I've renamed the existing `ensureElement ` (and all references to it) and created a new one that's what we need here. 32c8fa226

**Comment by EmilyBermudez88** [comment]
I'm looking through both ensureElement and ensureStartEndElements and now have a follow up question. I threw a console.log in while trying to understand what elements `isReactText()` is pulling. The description for onClose falls within these params, but I'm confused  why it isn't wrapped in a span when it is passed as an argument to `ensureElement()`? It is an array, so wouldn't it fall under the second if statement of `Array.isArray(content)`?
Screen Shot 2022-09-12 at 4 24 37 PM
Screen Shot 2022-09-12 at 4 25 06 PM
Screen Shot 2022-09-12 at 4 25 47 PM

**Comment by rpokorny** [comment]
> I'm looking through both ensureElement and ensureStartEndElements and now have a follow up question. I threw a console.log in while trying to understand what elements isReactText() is pulling. The description for onClose falls within these params, but I'm confused why it isn't wrapped in a span when it is passed as an argument to ensureElement()? It is an array, so wouldn't it fall under the second if statement of Array.isArray(content)?

I assume you are referring to the fact that `NxTableCell` passes its `children` through `ensureStartEndElements`.  While it is true that it does, if you look closely you'll see that the variable that holds (among other things) the result of that operation, `cellSortingContents`, is only used in the return value of `NxTableCell` when the cell is a sortable column header.  In the case that the `onClose` description cell falls into, the `children` are used directly and `cellSortingContents` is ignored.

**Comment by EmilyBermudez88** [comment]
>I assume you are referring to the fact that NxTableCell passes its children through ensureStartEndElements. While it is true that it does, if you look closely you'll see that the variable that holds (among other things) the result of that operation, cellSortingContents, is only used in the return value of NxTableCell when the cell is a sortable column header. In the case that the onClose description cell falls into, the children are used directly and cellSortingContents is ignored.


thanks for the clarification!

**Review by EmilyBermudez88 — APPROVED** [review]

**Pull request merged**
