### PR TITLE
nx-table background - RSC-417

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-417

### CODE REVIEW

**Comment by glenhunter** [comment]
Given what we have seen with what Jeffry did with RSC yesterday I think we should create and use a variable like `$nx-component-background-color` for this (and eventually other components) so that we can future-proof against the need for "dark mode"

**Comment by rpokorny** [comment]
> Given what we have seen with what Jeffry did with RSC yesterday I think we should create and use a variable like $nx-component-background-color for this (and eventually other components) so that we can future-proof against the need for "dark mode"

Sure.  That's bigger than this ticket though

**Comment by glenhunter** [comment]
> > Given what we have seen with what Jeffry did with RSC yesterday I think we should create and use a variable like $nx-component-background-color for this (and eventually other components) so that we can future-proof against the need for "dark mode"
> 
> Sure. That's bigger than this ticket though

It's not that much bigger, I'm just suggesting that instead of using `$nx-white` you create a new variable that has `$nx-white` mapped to it.

**Comment by rpokorny** [comment]
> It's not that much bigger, I'm just suggesting that instead of using $nx-white you create a new variable that has $nx-white mapped to it.

And then use that variable everywhere, including many places that aren't related to this PR

**Comment by glenhunter** [comment]
> > It's not that much bigger, I'm just suggesting that instead of using $nx-white you create a new variable that has $nx-white mapped to it.
> 
> And then use that variable everywhere, including many places that aren't related to this PR

No, I'm saying create it and use it here just for the tables. Now we have it and we can roll it out elsewhere later.

**Comment by rpokorny** [comment]
> No, I'm saying create it and use it here just for the tables. Now we have it and we can roll it out elsewhere later.

I've created another ticket and PR to set up the variable, and am using it in this PR in commit 
0fe63d6

**Review by glenhunter — APPROVED** [review]

**Pull request merged**
