### PR TITLE
Correct nx-btn-bar Margin - RSC-542

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-542

### CODE REVIEW

**Comment by glenhunter** [comment]
You removed the `nx-card` example with the button bar but not the SCSS was that intentional?

**Comment by rpokorny** [comment]
> You removed the nx-card example with the button bar but not the SCSS was that intentional?

No, I hadn't checked to see if there was any.  Is that what you're referring to? efa1ea10

**Comment by glenhunter** [comment]
> > You removed the nx-card example with the button bar but not the SCSS was that intentional?
> 
> No, I hadn't checked to see if there was any. Is this what you're referring to? [efa1ea1](https://github.com/sonatype/sonatype-react-shared-components/commit/efa1ea1084d21e3cad3a8b3c3c705cdc024f945c)

Yes

**Comment by glenhunter** [comment]
For the record I still think that it's a mistake removing the button bar styling from `nx-card`. I won't be in the least surprised if we end up adding it back in very soon.

**Review by glenhunter — APPROVED** [review]

**Pull request merged**
