### PR TITLE
change NxPageTitle.headings from div to hgroup - RSC-1084

### PR DESCRIPTION
**Pull request by EmilyBermudez88**
https://issues.sonatype.org/browse/RSC-1084

### CODE REVIEW

**Comment by entroform** [comment]
Hi Emily,
I think we need to update the test too, it should be inside `lib/src/components/__tests__/SimpleComponents.test.tsx`

**Comment by rpokorny** [comment]
Go ahead and do the version number bump and run CI before people review.  That way you will be sure you haven't missed anything.  For instance CI would have caught the need for the unit test update that @entroform mentioned.

**Comment by EmilyBermudez88** [comment]
> Hi Emily, I think we need to update the test too, it should be inside `lib/src/components/__tests__/SimpleComponents.test.tsx`

https://github.com/sonatype/sonatype-react-shared-components/pull/722/commits/a0ca3b153e1d7d676983b36abb6f7d6e1b971c9a

Thanks Andrew, should be fixed, but let me know

**Comment by entroform** [comment]
> > Hi Emily, I think we need to update the test too, it should be inside `lib/src/components/__tests__/SimpleComponents.test.tsx`
> 
> [a0ca3b1](https://github.com/sonatype/sonatype-react-shared-components/commit/a0ca3b153e1d7d676983b36abb6f7d6e1b971c9a)
> 
> Thanks Andrew, should be fixed, but let me know

That looks good! Thanks Emily!

**Review by rpokorny — APPROVED** [review]

**Pull request merged**
