### PR TITLE
Fixed Firefox focus artifact - RSC-702

### PR DESCRIPTION
**Pull request by entroform**
https://issues.sonatype.org/browse/RSC-702

### CODE REVIEW

**Review by rpokorny — APPROVED** [review]
Seems fixed but while testing it I'm getting an odd thing where the left-side list overall is in the tab order for some reason, in between the filter input and the first item.  Does anyone else see that?  That would be a separate bug

**Comment by rpokorny** [comment]
> Seems fixed but while testing it I'm getting an odd thing where the left-side list overall is in the tab order for some reason

Oh I think it's because it's scrollable.  Is that just a firefox thing, that scroll boxes get added to the tab order?

**Comment by entroform** [comment]
> > Seems fixed but while testing it I'm getting an odd thing where the left-side list overall is in the tab order for some reason
> 
> Oh I think it's because it's scrollable. Is that just a firefox thing, that scroll boxes get added to the tab order?

Hmm interesting. Yeah it is just a Firefox thing it seems. Is this something we should add for accessibility on other browsers? 🤔  https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/

**Comment by rpokorny** [comment]
> Hmm interesting. Yeah it is just a Firefox thing it seems. Is this something we should add for accessibility on other browsers? thinking https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/

From that page (emphasis mine):

> Instead, focus must be moved either to the scrollable element itself **or to a child element** within the scrollable element. Then the content can be scrolled using the keyboard’s arrow keys.

In chrome, when one of the list items is focused, the arrow keys do scroll the list.  So I think we're fine.

**Pull request merged**
