### PR TITLE
Update primary text color - RSC-276

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-276

### CODE REVIEW

**Comment by glenhunter** [comment]
It seems to me that most of the instances of `color: $nx-text-color;` are now redundant and could be removed since the elements in question will pick up the color from `.nx-body`.

**Comment by rpokorny** [comment]
> It seems to me that most of the instances of color: $nx-text-color; are now redundant and could be removed since the elements in question will pick up the color from .nx-body.

I did that, but I'll make another pass at it if you think I missed some

**Comment by glenhunter** [comment]
> > It seems to me that most of the instances of color: $nx-text-color; are now redundant and could be removed since the elements in question will pick up the color from .nx-body.
> 
> I did that, but I'll make another pass at it if you think I missed some

I see lots. Basically anywhere that `$nx-text-color-light` changed to `$nx-text-color` I think could be removed

**Comment by rpokorny** [comment]
> I see lots. Basically anywhere that $nx-text-color-light changed to $nx-text-color I think could be removed

The majority of them are necessary, but I found a few that could be removed: 7ba643b7

**Comment by rpokorny** [comment]
> The majority of them are necessary, but I found a few that could be removed: 7ba643b

To clarify, I also didn't bother removing redundancy in components that have their own yet-to-be-completed refactorings: counter, list, and table

**Review by glenhunter — APPROVED** [review]

**Pull request merged**
