### PR TITLE
useScrollSpy - RSC-995

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-995

### CODE REVIEW

**Review by JenniKobylski — COMMENTED** [review]
+1 from design

**Comment by JenniKobylski** [comment]
+1 from design

**Comment by JenniKobylski** [comment]
+1 from design

**Review by JenniKobylski — APPROVED** [review]

**Review by entroform — APPROVED** [review]
This is neat! LGTM

**Pull request merged**
