### PR TITLE
NxTree Dark Mode - RSC-1016

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-1016

### CODE REVIEW

**Comment by cindyko226** [comment]
In the mockups, the variation 1 uses `nx-indigo-70` for tree line while variation 2/3/4 use `nx-indigo-60`, I think we should confirm with design and update the mockups accordingly.

**Comment by momah000** [comment]
It should be nx-indigo-70 not nx-indigo-60. Sorry for the mix up

**Review by cindyko226 — APPROVED** [review]

**Comment by EmilyBermudez88** [comment]
In light mode, the colour of non-link tree items are bolded and black, but in the gallery they're set to the normal `grey-30` text colour (and regular 400 weight). Is it a mistake in the mocks?

**Comment by rpokorny** [comment]
> In light mode, the colour of non-link tree items are bolded and black, but in the gallery they're set to the normal grey-30 text colour (and regular 400 weight). Is it a mistake in the mocks?

The bold is a mistake in the mocks I'm pretty certain.  I'll go back and check the colors again though

**Comment by rpokorny** [comment]
> It looks like non-link tree items in dark mode are indigo-90, but currently set to indigo-80

> In light mode, the colour of non-link tree items are bolded and black, but in the gallery they're set to the normal grey-30 text colour (and regular 400 weight). Is it a mistake in the mocks?

As confirmed in WW, the mockups have problems but the default text in the tree should be regular text style

**Review by EmilyBermudez88 — APPROVED** [review]

**Pull request merged**
