### PR TITLE
Fix NxTile header height and spacings issues - RSC-823

### PR DESCRIPTION
**Pull request by entroform**
https://issues.sonatype.org/browse/RSC-823

### CODE REVIEW

**Comment by rpokorny** [comment]
Incorrect in the case where this a title and subtitle but no action buttons.  I believe instead of changing the height of the entire header, you need to change the height of its first grid row.

**Comment by rpokorny** [comment]
> Incorrect in the case where this a title and subtitle but no action buttons. I believe instead of changing the height of the entire header, you need to change the height of its first grid row.

Going along with that, I'm not sure the `min-height` on the header overall is still necessary.  For that matter, I'm not super clear on why it was necessary previously.

**Review by avnvbhatta — APPROVED** [review]

**Comment by rpokorny** [comment]
I didn't see my comments above get addressed

**Comment by entroform** [comment]
> I didn't see my comments above get addressed

Sorry about that: here's a new PR addressing your comments:
https://github.com/sonatype/sonatype-react-shared-components/pull/674

**Pull request merged**
