### PR TITLE
Dark Mode - NxAccordion - RSC-1002

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1002

This PR also fixes a bug in light mode where it was using a hardcoded color for the divider.

### CODE REVIEW

**Comment by rpokorny** [comment]
This ticket also needs to update the tile accordion container color:
image

**Comment by EmilyBermudez88** [comment]
replace `dark` with `stark` on line 29 & 68

**Comment by avnvbhatta** [comment]
> This ticket also needs to update the tile accordion container color: image

What is the correct color for this? I don't see anything in the mocks.

**Comment by avnvbhatta** [comment]
> replace `dark` with `stark` on line 29 & 68

Replaced here: 47cd0fbf5180c0aee7eacc65f6374c92a320204e

**Review by rpokorny — APPROVED** [review]

**Pull request merged**
