### PR TITLE
Light Mode Interaction States - Toggle - RSC-1484

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1484

### CODE REVIEW

**Review by entroform — COMMENTED** [review]
I'm not sure if this is a issue, but should we delete the previous snapshots that were renamed?

**Comment by avnvbhatta** [comment]
> I'm not sure if this is a issue, but should we delete the previous snapshots that were renamed?

Good idea! Deleted the older ones here: a834778120d1e5165e5ea591fdeed21eebd9a288

**Comment by EmilyBermudez88** [comment]
In the snapshots, the focus line around the buttons are cut off. Can we expand the photo to get the whole focus border? 
Screenshot 2023-02-23 at 10 56 06 AM

**Comment by avnvbhatta** [comment]
> In the snapshots, the focus line around the toggles are cut off. They are the same on `main`, but can we expand the photo to get the whole focus border? Screenshot 2023-02-23 at 10 56 06 AM

Yup. Changed here: 48d5be2fc0787fbb1cb706e707ed41ee2b8aac92

**Comment by EmilyBermudez88** [comment]
I don't think there is a visual test for when the toggle is clicked/on and hovered

**Comment by EmilyBermudez88** [comment]
Other than https://github.com/sonatype/sonatype-react-shared-components/pull/977#issuecomment-1443772028, LGTM!

**Review by EmilyBermudez88 — APPROVED** [review]

**Pull request merged**
