### PR TITLE
Rename nx-root-container - RSC-89

### PR DESCRIPTION
**Pull request by glenhunter**
https://issues.sonatype.org/browse/RSC-89

Simple change to make the intention of this wrapping class clearer. 

`nx-root-container` isn't very clear as a class name, the purpose of this `<div>` is to act as a container for `.nx-page-sidebar` and `.nx-page-main`. I think `.nx-page-content-container` is more clear in its intent.

### CODE REVIEW

**Comment by Blacktiger** [comment]
Personally I'd expect the main content to go into `nx-page-content-container` based on the name. `nx-page-main` feels like what the whole page would go into. :shrug:

**Comment by glenhunter** [comment]
> Personally I'd expect the main content to go into `nx-page-content-container` based on the name. `nx-page-main` feels like what the whole page would go into. 🤷

I drew up the attached image to clarify the class names. Now is the time to make these changes, before the styles become too embedded in projects to easily change.

Screen Shot 2020-04-24 at 4 00 19 PM

**Comment by Blacktiger** [comment]
> So I think what you're suggesting is that `nx-page-main` should become something like `nx-page-content`?

I'm just saying that's what I was expecting I guess. That might be because in nxrm we don't have a content sidebar really (sometimes an info panel on the right) because our left sidebar is used for navigation. We only have a main content area, so I guess the names are confusing to me. I think we should make sure the page layout classes/components include that diagram somewhere so people can figure out how things are structured since some things may not be clear just based on the name.

**Comment by Blacktiger** [comment]
> > So I think what you're suggesting is that `nx-page-main` should become something like `nx-page-content`?

So maybe the class names should be `.nx-body`, `.nx-body-container`, `.nx-page` (new div needed for this), `.nx-page-header`, `.nx-page-container`, `.nx-page-container-sidebar` (or maybe `.nx-page-sidebar`), and `.nx-page-container-content` (or maybe `.nx-page-content`)? It would be nice if the class names related to the dom structure a bit more clearly to aid in understanding where/how the class should be used.

**Comment by rpokorny** [comment]
> So maybe the class names should be .nx-body, .nx-body-container, .nx-page (new div needed for this), .nx-page-header, .nx-page-container, .nx-page-container-sidebar (or maybe .nx-page-sidebar), and .nx-page-container-content (or maybe .nx-page-content)? It would be nice if the class names related to the dom structure a bit more clearly to aid in understanding where/how the class should be used.

Something along thesee lines seems sensible to me, except that I don't think an additional div is necessary; we can just change `.nx-body-container` to `.nx-page`

**Comment by glenhunter** [comment]
> > So maybe the class names should be .nx-body, .nx-body-container, .nx-page (new div needed for this), .nx-page-header, .nx-page-container, .nx-page-container-sidebar (or maybe .nx-page-sidebar), and .nx-page-container-content (or maybe .nx-page-content)? It would be nice if the class names related to the dom structure a bit more clearly to aid in understanding where/how the class should be used.
> 
> Something along these lines seems sensible to me, except that I don't think an additional div is necessary; we can just change `.nx-body-container` to `.nx-page`

I've tried to take the various comments into account and make the terms as clear as possible. I changed "container" to "wrapper" because I think that "wrapper" is a bit clearer that the `<div>` in question is meant to "wrap around" other content, but not have any other content itself.

Screen Shot 2020-04-27 at 10 38 13 AM

**Comment by rpokorny** [comment]
> I've tried to take the various comments into account and make the terms as clear as possible. I changed "container" to "wrapper" because I think that "wrapper" is a bit clearer that the <div> in question is meant to "wrap around" other content, but not have any other content itself.

What was wrong with just `nx-page` for the top one (what you no have as `nx-page-wrapper`)?

**Comment by rpokorny** [comment]
I notice we have a familiar pattern here: header, content, and then footer.  Just like in `nx-tile` and `nx-modal`.  I think it would be valuable to align the names even more closely to the way they are in those cases, by renaming `nx-page-content-wrapper` to simply `nx-page-content`.

**Comment by glenhunter** [comment]
> I notice we have a familiar pattern here: header, content, and then footer. Just like in `nx-tile` and `nx-modal`. I think it would be valuable to align the names even more closely to the way they are in those cases, by renaming `nx-page-content-wrapper` to simply `nx-page-content`.

Yes, you're right, I lost sight of that a bit, but I think the naming of this is clearer:
Screen Shot 2020-04-27 at 10 56 05 AM

My goal with the "wrapper" suffix was to try and make it clear that wrappers don't hold content, they wrap other `<div>`s which contain the content. Keeping a consistent:
Parent
-- Header
-- Content
-- Footer
naming structure probably does a better job of that.

**Comment by mpiggott** [comment]
At least how we use it in NXRM the sidebar isn't really part of the page content anymore than the header or the footer

**Comment by Blacktiger** [comment]
> At least how we use it in NXRM the sidebar isn't really part of the page content anymore than the header or the footer

We probably can't use these layout classes in nxrm (or at least not all of them) until we rethink the navigation/layout anyway. I suspect we'll need to have our own custom layout components/classes at least initially.

**Comment by glenhunter** [comment]
> > At least how we use it in NXRM the sidebar isn't really part of the page content anymore than the header or the footer
> 
> We probably can't use these layout classes in nxrm (or at least not all of them) until we rethink the navigation/layout anyway. I suspect we'll need to have our own custom layout components/classes at least initially.

My thinking is that these styles are mostly for new projects and IQ. Having spent some time in the RM codebase it seems unlikely that you'd be able to implement such extreme changes to your page structure in the near or even medium term.

**Comment by glenhunter** [comment]
It's also worth pointing out that these page layout styles are not meant to be proscriptive/mandatory. They are meant to be an aid in getting a new project up and running quickly. If existing projects can use them for refactoring or new development that's a bonus.

**Comment by rpokorny** [comment]
the header is currently `nx-header` not `nx-page-header`.

**Comment by glenhunter** [comment]
> the header is currently `nx-header` not `nx-page-header`.

Changed here: https://github.com/sonatype/sonatype-react-shared-components/pull/14/commits/995ce5dd3c3d99afbaee683cc6532bf2c1b4a004

**Pull request merged**
