### PR TITLE
Dark Mode: System Notice - RSC-1042

### PR DESCRIPTION
**Pull request by rpokorny**
https://issues.sonatype.org/browse/RSC-1042

Note: Many visual tests that include NxSystemNotice also include NxGlobalSidebar and so cannot be committed yet.  Unfortunately, this includes the one with the `--alert` styling.

### CODE REVIEW

**Comment by cindyko226** [comment]
Missing variables documentation.

**Comment by rpokorny** [comment]
> Missing variables documentation.

f8496acf3

**Review by EmilyBermudez88 — APPROVED** [review]
LGTM. Perhaps you could just make a note to update the remaining NxSystemNotice snapshot in the NxGlobalSidebar ticket?

**Comment by rpokorny** [comment]
> Perhaps you could just make a note to update the remaining NxSystemNotice snapshot in the NxGlobalSidebar ticket?

I'll put a comment on https://github.com/sonatype/sonatype-react-shared-components/pull/1091 after I merge this

**Pull request merged**
