### PR TITLE
Light Mode Interaction States - NxGlobalSidebar - RSC-1471

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1471

### CODE REVIEW

**Comment by EmilyBermudez88** [comment]
It's odd, even though it's explicitly laid out in the CSS, the text colour of `--nx-global-sidebar__navigation-text` is getting overridden and is blue on click. This doesn't seem to happen when you set the link to an active state in the dev tools, just when you physically click the navigation link.

**Comment by EmilyBermudez88** [comment]
Is it worth doing visual tests for interaction states here? Some of the styling is unique to nxGlobalSidebar which may be useful, but I can also see that it can get out of hand testing every little thing. What are your thoughts?

**Comment by EmilyBermudez88** [comment]
One more small thing- it looks like `:hover` is overriding the `:active` background colour

**Comment by EmilyBermudez88** [comment]
Screenshot 2023-03-13 at 11 56 10 AM

So in the scrolling example, there is a problem with the interaction states of the NxCollapsibleItem. I don't think there are any guidelines regarding what can or cannot be included in `__other-content`, so not sure how to deal with the interaction states here. Is this something to be dealt with here, or in NxCollapsibleItems?

**Comment by avnvbhatta** [comment]
> Screenshot 2023-03-13 at 11 56 10 AM
> 
> So in the scrolling example, there is a problem with the interaction states of the NxCollapsibleItem. I don't think there are any guidelines regarding what can or cannot be included in `__other-content`, so not sure how to deal with the interaction states here. Is this something to be dealt with here, or in NxCollapsibleItems?

Looks like this is an issue currently in production too. I think there definitely needs to be some sort of guidance in terms of what can and cannot be included in `__other-content`. For one, I think at the very least, there should be designs with collapsible items within `.nx-global-sidebar` as well. Currently, there are mocks for collapsible items within a `.nx-page-sidebar`. For that reason, I think we should deal with this issue in  `NxCollapsibleItems` and not here.

**Comment by EmilyBermudez88** [comment]
> Looks like this is an issue currently in production too. I think there definitely needs to be some sort of guidance in terms of what can and cannot be included in `__other-content`. For one, I think at the very least, there should be designs with collapsible items within `.nx-global-sidebar` as well. Currently, there are mocks for collapsible items within a `.nx-page-sidebar`. For that reason, I think we should deal with this issue in `NxCollapsibleItems` and not here.

So for now, is your suggestion we move this ahead as approved, and make 2 tickets: one to add in guidance for what should/could be included in `__other-content` and update the mocks, and another to fix the interaction states problem for `NxCollapsibleItems` in a sidebar (since it's now merged)?

**Comment by avnvbhatta** [comment]
> > Looks like this is an issue currently in production too. I think there definitely needs to be some sort of guidance in terms of what can and cannot be included in `__other-content`. For one, I think at the very least, there should be designs with collapsible items within `.nx-global-sidebar` as well. Currently, there are mocks for collapsible items within a `.nx-page-sidebar`. For that reason, I think we should deal with this issue in `NxCollapsibleItems` and not here.
> 
> So for now, is your suggestion we move this ahead as approved, and make 2 tickets: one to add in guidance for what should/could be included in `__other-content` and update the mocks, and another to fix the interaction states problem for `NxCollapsibleItems` in a sidebar (since it's now merged)?

Yes, so one ticket to update the global sidebar mocks to include guidance on what to include in the "other content" section. Another ticket to update the `NxCollapsibleItems` mocks to include usage within the global sidebar.

**Comment by EmilyBermudez88** [comment]
So all looks good to me. I figure I will just bring it up based on WW this morning, but do you mind the square focus border around the open/close icon? It's not nearly as jarring as NxFileUpload, but figured I'd just raise the question in case you feel strongly about changing it. Otherwise as I said, it LGTM

**Comment by avnvbhatta** [comment]
> So all looks good to me. I figure I will just bring it up based on WW this morning, but do you mind the square focus border around the open/close icon? It's not nearly as jarring as NxFileUpload, but figured I'd just raise the question in case you feel strongly about changing it. Otherwise as I said, it LGTM

I guess in this case the square is a lot more subtle than NxFileUpload. So I'm fine to leave it as it is.

**Review by EmilyBermudez88 — APPROVED** [review]

**Pull request merged**
