### PR TITLE
Hide text filter input - Collapsible Multi/Radio Selects - RSC-1439

### PR DESCRIPTION
**Pull request by avnvbhatta**
https://issues.sonatype.org/browse/RSC-1439

### CODE REVIEW

**Comment by entroform** [comment]
Just wondering if we should add a test for this.

**Comment by avnvbhatta** [comment]
> Just wondering if we should add a test for this.

Yep, but we decided not to add enzyme tests. I've created another ticket for it:
https://issues.sonatype.org/browse/RSC-1457

**Review by entroform — APPROVED** [review]
LGTM :)

**Comment by rpokorny** [comment]
> Yep, but we decided not to add enzyme tests. I've created another ticket for it:
https://issues.sonatype.org/browse/RSC-1457

Seeing as the fix here was CSS I have to think the only test that can properly verify this would be a visual test, not RTL

**Pull request merged**
